version: '2'

networks:
  app:
    driver: bridge

services:
  funhouse:
    env_file:
      - .env
    build: .
    ports:
      - "3000:3000"
    networks:
      - app

  mongodb:
    image: 'bitnami/mongodb:3.6.6'
    volumes:
      - /data:/bitnami
    networks:
      - app