version: '2'

networks:
  funhouse:
    driver: bridge

services:
  funhouse:
    env_file:
      - .env
    build: .
    ports:
      - "3000:3000"
    volumes:
      - /mnt/wisconsin/funhouse_users:/fh_users
    networks:
      - funhouse
